ARG PHP_VERSION='8.2'
ARG BUILD_MODE="with-config"
FROM ulysse699/composer:latest AS vendors-installation

ARG COMPOSER_AUTH=""

ENV \
COMPOSER_ALLOW_SUPERUSER="1" \
COMPOSER_ALLOW_XDEBUG="0" \
COMPOSER_CACHE_DIR="/var/cache/composer" \
COMPOSER_AUTH="${COMPOSER_AUTH}"

VOLUME ["/var/cache/composer"]

COPY .composer /var/cache/composer

COPY src /src


FROM ulysse699/app-php:latest as magento-with-vendors

USER root

RUN apt-get update
RUN apt-get install -y xxd
RUN apt-get install -y cron
RUN apt-get install -y 
RUN apt-get install -y default-mysql-client

COPY --chown=rootless:rootless src /var/www

COPY --chown=rootless:rootless system /


    # Créer les fichiers de log avec les bonnes permissions
RUN touch /var/www/var/log/cron.log && \
    touch /var/mycron && \
    chmod 644 /var/www/var/log/cron.log && \
    chmod 644 /var/mycron

RUN chown -R rootless:rootless /var/mycron

RUN set -eux; \
echo "/docker/d-bootstrap-magento.sh" >> /docker/d-bootstrap.list; \
chmod +x /docker/d-bootstrap-magento.sh

USER rootless

RUN echo '* * * * * /usr/local/bin/php /var/www/bin/magento cron:run 2>&1 | grep -v "Ran jobs by schedule" >> /var/www/var/log/cron.log' \
    > /var/mycron && \
    crontab /var/mycron