apiVersion: v1
kind: Pod
metadata:
  name: elasticsearch
  labels:
    app: elasticsearch
spec:
  containers:
  - image: elasticsearch:7.5.2
    name: elasticsearch
    env:
    - name: discovery.type
      value: single-node
    volumeMounts:
    - name: data
      mountPath: /usr/share/elasticsearch/data
    ports:
    - containerPort: 9200
  volumes:
    - name: data
      persistentVolumeClaim:
        claimName: data-elasticsearch
