apiVersion: v1
kind: ConfigMap
metadata:
  creationTimestamp: null
  name: env-file
data:
  env.php: |
    <?php
    return [
        'backend' => [
            'frontName' => 'admin'
        ],
        'cache' => [
            'graphql' => [
                'id_salt' => '3BRNTJ2pLj4vnuc5UiquIRi14TidbQ2U'
            ],
            'frontend' => [
                'default' => [
                    'id_prefix' => 'a7d_',
                    'backend_options' => [
                        'server' => 'redis-cache',
                        'port' => '6379'
                    ]
                ],
                'page_cache' => [
                    'id_prefix' => 'a7d_',
                    'backend' => 'Magento\\Framework\\Cache\\Backend\\Redis',
                    'backend_options' => [
                        'server' => 'redis-cache',
                        'database' => '1',
                        'port' => '6379',
                        'password' => '',
                        'compress_data' => '0',
                        'compression_lib' => ''
                    ]
                ]
            ],
            'allow_parallel_generation' => false
        ],
        'remote_storage' => [
            'driver' => 'file'
        ],
        'queue' => [
            'consumers_wait_for_messages' => 1
        ],
        'crypt' => [
            'key' => '548867440510b4d6c7a46d637748c563'
        ],
        'db' => [
            'table_prefix' => '',
            'connection' => [
                'default' => [
                    'host' => 'mysql',
                    'dbname' => 'magento',
                    'username' => 'rootless',
                    'password' => 'nopassword',
                    'model' => 'mysql4',
                    'engine' => 'innodb',
                    'initStatements' => 'SET NAMES utf8;',
                    'active' => '1',
                    'driver_options' => [
                        1014 => false
                    ]
                ]
            ]
        ],
        'resource' => [
            'default_setup' => [
                'connection' => 'default'
            ]
        ],
        'x-frame-options' => 'SAMEORIGIN',
        'MAGE_MODE' => 'default',
        'session' => [
            'save' => 'redis',
            'redis' => [
                'host' => 'redis-session',
                'port' => '6379',
                'password' => '',
                'timeout' => '2.5',
                'persistent_identifier' => '',
                'database' => '2',
                'compression_threshold' => '2048',
                'compression_library' => 'gzip',
                'log_level' => '1',
                'max_concurrency' => '6',
                'break_after_frontend' => '5',
                'break_after_adminhtml' => '30',
                'first_lifetime' => '600',
                'bot_first_lifetime' => '60',
                'bot_lifetime' => '7200',
                'disable_locking' => '0',
                'min_lifetime' => '60',
                'max_lifetime' => '2592000',
                'sentinel_master' => '',
                'sentinel_servers' => '',
                'sentinel_connect_retries' => '5',
                'sentinel_verify_master' => '0'
            ]
        ],
        'lock' => [
            'provider' => 'db'
        ],
        'directories' => [
            'document_root_is_pub' => true
        ],
        'cache_types' => [
            'config' => 1,
            'layout' => 1,
            'block_html' => 1,
            'collections' => 1,
            'reflection' => 1,
            'db_ddl' => 1,
            'compiled_config' => 1,
            'eav' => 1,
            'customer_notification' => 1,
            'config_integration' => 1,
            'config_integration_api' => 1,
            'full_page' => 1,
            'config_webservice' => 1,
            'translate' => 1
        ],
        'install' => [
            'date' => 'Sun, 24 Sep 2023 18:15:37 +0000'
        ]
    ];
