apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: data-magento
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: do-block-storage
  volumeMode: Filesystem