apiVersion: v1
kind: Service
metadata:
  name: mailhog
spec:
  selector:
    app: mailhog
  type: LoadBalancer
  ports:
    - port: 1025
      name: port1
      targetPort: 1025
    - port: 8025
      name: port2
      targetPort: 8025
