apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: data-mysql
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
  storageClassName: do-block-storage
  volumeMode: Filesystem