apiVersion: v1
kind: Pod
metadata:
  name: phpmyadmin
  labels:
    app: phpmyadmin
spec:
  containers:
  - image: phpmyadmin/phpmyadmin:latest
    name: phpmyadmin
    env:
    - name: PMA_HOST
      value: mysql
    - name: MYSQL_ROOT_PASSWORD
      value: root
    - name: PMA_USER
      value: rootless
    - name: PMA_PASSWORD
      value: nopassword
