apiVersion: v1
kind: Pod
metadata:
  name: redis-cache
  labels:
    app: redis-cache
spec:
  containers:
    - image: redis:7.0
      name: redis-cache
      volumeMounts:
        - name: redis-cache
          mountPath: /data
  volumes:
    - name: redis-cache
      persistentVolumeClaim:
        claimName: data-redis-cache
