http:
  routers:
    dashboard:
      rule: "Host(`traefik.dev.local`)"
      service: "api@internal"
      entryPoints:
        - "websecure"
      tls: {}

# Définition des certificats TLS
tls:
  certificates:
    - certFile: /certs/local.crt
      keyFile: /certs/local.key
      stores:
        - default